### ISSUE TITLE
Celsius vs. Fahrenheit

### ISSUE THREAD

**Issue by maelstromchanneled** [Kienz/homebridge-speedtest-net#4]
Thanks again for your help getting me up and running.

The sensor is displaying now in Home App and I can see the following log in root/accessories:

> {"firstEntry":0,"lastEntry":5,"usedMemory":5,"refTime":609839688.26,"initialTime":1588146888.26,"history":["noValue",{"time":1588146888.26,"setRefTime":1},{"time":1588146888.26,"temp":565.38,"humidity":17.37,"pressure":8},{"time":1588147368.265,"temp":565.38,"humidity":17.37,"pressure":8},{"time":1588147848.273,"temp":565.38,"humidity":17.37,"pressure":8},{"time":1588148328.277,"temp":565.38,"humidity":17.37,"pressure":8}]}

So, speedtest is consistently reporting 565.38 Mbps download speed.

The problem is that this is somehow being reported into Homebridge as celsius, but my Home preference is set to Fahrenheit.  Somewhere, the 565.38 _degrees celsius_ is being converted to 1049.684 _degrees Fahrenheit_, and this is being rounded in the final display.

<img width="137" alt="Screen Shot 2020-04-29 at 1 33 33 AM" src="https://user-images.githubusercontent.com/64129452/80576093-7437f200-89b9-11ea-97c2-aa0069d48c23.png">

Is there a way to set the units preference in the config?

**Comment by Kienz** [comment]
Its not possible (afik) because the Home.app converts celsius <-> fahrenheit automatically. In the Eve.app it should be displayed correct. Sorry.

**Comment by blaflen** [comment]
Actually, what I am requesting is a little different.  This issue is being caused by us using a temperature sensor to report network speed.  Everything in the chain of custody is doing the right thing _from a temperature perspective_ -- the result I am getting is the right value _in Fahrenheit_, it just doesn't accurately report network speed.  HomeKit uses Celsius under the hood, regardless of user viewing preferences.

What I propose we do is modify the code here:

>     this.Sensor.getCharacteristic(Characteristic.CurrentTemperature)
>       .setProps({
>         unit: 'Mbps',
>         maxValue: 9999,
>         minValue: 0,
>         minStep: 0.01,
>         perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
>       })
>       .updateValue(this.dlspeed);

If user has specified Fahrenheit in their plugin config, then the last line should be 

>       .updateValue((this.dlspeed-32)*5/9);

The net result is that HomeKit will undo this mapping when displaying for Fahrenheit users.

**Comment by blaflen** [comment]
One more thought.  If you are willing to make the above change, another small tweak would be to let users put their theoretical max network speed (e.g., from their ISP) in the config.  Then, instead of reporting absolute network speed, the temperature sensor could report % max.  At least for my household, being able to quickly look at the temperature sensor in Home and see that the network is at 80% (or 10%, or 0%) is a great, quick way to assess the network health.

**Comment by maelstromchanneled** [comment]
Requests are addressed in #6
